### ISSUE TITLE
New product not visible

### ISSUE THREAD

**Issue by msebzda** [pj28105/Sales-and-Inventory-Management-System#1] opened 2022-01-13 18:00 UTC
After adding a new product it only appears in the "Items" page but it's not possible to add this product to the invoice (it's not visible in the dropdown list in "invoice" page.

![1](https://user-images.githubusercontent.com/92209184/149383880-46b3bc4b-40a5-4149-ae9f-efc83edf6f66.png)
![2](https://user-images.githubusercontent.com/92209184/149383875-7e5cfd99-6137-4cf8-b453-0f8ac749cfc6.png)
![3](https://user-images.githubusercontent.com/92209184/149383871-40aeaa3e-1f1f-4392-bf9e-a342871ddc46.png)

**Comment by pj28105** [comment] 2022-04-16 18:32
Hey @msebzda ,

The issue is **not reproducible**. 
Closing this.

**Closed as completed** 2022-04-16 18:32 UTC
Labels: question
